name: deneme
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.12.1
  firebase_auth: 5.5.1
  cloud_firestore: 5.6.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  google_sign_in: 6.3.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Animation.json
    - assets/heartify1.png
    - assets/google_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/heart.png"
